version: '3.8'

services:
  ocr-app:
    # Build the production image using the multi-stage Dockerfile
    build:
      context: .
      dockerfile: Dockerfile

    # Load environment variables for Supabase and OCR providers
    env_file:
      - .env.local

    # Expose the app on port 3000
    ports:
      - '3005:3000'

    restart: always